my_website_dj/blog/urls.py
from django.urls import path 
from . import views
from .views import CreatePostView ,UpdatePostView , DeletePostView
urlpatterns = [
    path('',views.index,name='index'),
    path('new_post/',CreatePostView.as_view(),name='new_post'),
    path('detail/<int:post_id>/',views.detail_post,name='detail'),
    path('detail/<slug:pk>/update/',UpdatePostView.as_view(),name='update_post'),
    path('detail/<slug:pk>/delete/',DeletePostView.as_view(),name='delete_post'),
] 

my_website_dj/my_website_dj/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("blog.urls")),
    path('',include("user.urls")),
]

my_website_dj/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

class Post(models.Model):
    content_post = models.TextField(max_length=10000)
    date_post = models.DateTimeField(default=timezone.now)
    update_post = models.DateTimeField(auto_now=True)
    auth = models.ForeignKey(User,on_delete=models.CASCADE )
    def __str__(self):
        return str(self.content_post)

    def get_absolute_url(self):
        return reverse('detail',args=[self.pk ])
    class Meta:
        ordering = ('-date_post', )



class Comment(models.Model):

 
    name = models.CharField(max_length=100 ,verbose_name='أسم المستخدم ')
    email = models.EmailField(verbose_name='ألبريد ألالكتروني')
    content_comment = models.TextField(max_length=5000,verbose_name='محتوى التعليق ')
    date_comment = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    post = models.ForeignKey(Post,on_delete=models.CASCADE , related_name='comments')

    def __str__(self):
        return f'تم التعليق بواسطة {self.name} على {self.content_comment}'

    class Meta:
        ordering = ('date_comment',)

my_website_dj/blog/forms.py
from django import forms 
from blog.models import Comment
from .models import Post

class NewComment(forms.ModelForm):
    username = forms.CharField(max_length=99,label='أسم المستخدم ',widget=forms.TextInput(attrs={'class':"form-control mt-2"}))
    content_comment = forms.CharField(max_length=99,label='التعليق ',widget=forms.TextInput(attrs={'class':"form-control mt-2"}))
    email = forms.CharField(max_length=99,label='البريد الألكتروني',widget=forms.EmailInput(attrs={'class':"form-control mt-2"}))
    
    class Meta:
        model = Comment
        fields = ('username','content_comment','email')

        
class CreateFormPost(forms.ModelForm):
    content_post = forms.CharField(label='منشور جديد',widget=forms.Textarea)
    class Meta:
        model = Post
        fields = ['content_post']

my_website_dj/blog/views.py
from pyexpat import model
from django.shortcuts import render , get_object_or_404 , redirect
from .models import Post , Comment
from .forms import NewComment , CreateFormPost
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView ,UpdateView , DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin , UserPassesTestMixin
def index (request):
    context = {
        'posts':Post.objects.all()
    }
    return render(request,'blog/index.html',context)




@login_required(login_url='login')
def detail_post(request,post_id):
    post = get_object_or_404(Post,pk=post_id)
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        form_comment = NewComment(data=request.POST)
        if form_comment.is_valid():
            new_comment = form_comment.save(commit=False)
            new_comment.post = post
            new_comment.save()
            form_comment = NewComment()
    else:        
        form_comment = NewComment()
    context ={
        'post':post,
        'comments':comments,
        'form_comment':NewComment()
    }
    return render(request,'blog/detail_post.html',context)


class CreatePostView(LoginRequiredMixin,CreateView):
    model = Post
    # fields = ['content_post']
    template_name = 'blog/new-post.html'
    form_class = CreateFormPost 
    def form_valid(self, form):
        form.instance.auth = self.request.user
        return super().form_valid(form)

class UpdatePostView(UserPassesTestMixin,LoginRequiredMixin,UpdateView):
    # fields = ['content_post']
    model = Post
    template_name = 'blog/update_post.html'
    form_class = CreateFormPost 
    def form_valid(self, form):
        form.instance.auth = self.request.user
        return super().form_valid(form)
    def test_func(self):
        post = self.get_object()

        if self.request.user == post.auth:
            return True
        return False

class DeletePostView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.auth:
            return True
        return False

my_website_dj/templates/blog/detail_post.html
{% extends 'base.html' %} {% load static %} 
{% block content %}
<main class="main">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <ul class="list-group posts">
          <!-- Start post -->
          <li class="list-group-item post my-2">
            <div class="user-info d-flex position-relative justify-content-between align-items-center">
              <div class="d-flex justify-content-between align-items-center">
                <a href="#" class="user text-decoration-none d-flex align-items-center">
                  <img
                    src="{{post.auth.profile.img.url}}"
                    class="img-fluid rounded-circle"
                    alt=""
                  />
                  <div class="mx-2"><small>{{post.auth}}</small><br /></div>
                </a>
                <small class="position-absolute data-time">
                  {{post.date_post}}
                </small>
              </div>
              <div class="dropdown">
                <i
                  class="fa-solid fa-ellipsis fs-5"
                  type="button"
                  id="dropdownMenuButton1"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                </i>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#share">مشاركة</a></li>
                  {% if post.auth == user  %}
                  <li><a class="dropdown-item" href="{% url 'update_post' post.id %}">تعديل المنشور</a></li>
                  <li><a class="dropdown-item" href="{% url 'delete_post' post.pk  %}">حذف</a></li>
                  {% endif %}
                  <li><a class="dropdown-item" href="#">حظر</a></li>
                  <li><a class="dropdown-item" href="#">أخفاء المنشور</a></li>
                  <li><a class="dropdown-item" href="#">ٌأبلاغ</a></li>
                </ul>
              </div>
            </div>
            <div class="content-post my-2 ">
              <p class="my-3 lh-lg fs-4">{{post.content_post}}</p>
            </div>
            <ul
              class="icons list-group flex-row justify-content-around position-relative"
            >
              <li class="list-group-item like-post active">
                <i class="fa-solid fa-thumbs-up"></i>
                <small>أعجاب</small>
              </li>
              <button
                class="btn-share"
                type="button"
                data-bs-toggle="modal"
                data-bs-target="#share"
              >
                <i class="fa-solid fa-share-from-square"></i>
                <small>مشاركة</small>
              </button>
            </ul>

            <div class="box-comments position-absolute w-100 overflow-hidden z-index-100">
                <div class="modal fade w-100"id="share" tabindex="-1" aria-labelledby="share-title" aria-hidden="true" >
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="share-title">
                          مشاركة المنشور على ....
                        </h5>
                        <button
                          type="button"
                          class="btn-close m-0"
                          data-bs-dismiss="modal"
                          aria-label="Close"
                        ></button>
                      </div>
                      <div class="modal-body">
                        <span class="rounded-circle copy-link fs-2"
                          ><i class="fa-solid fa-copy"></i
                        ></span>
                      </div>
                    </div>
                  </div>
                </div>
            </div>

            <div class="row mt-3 pt-4 border">
              <form class="w-100" method='POST'>
                {% csrf_token %}
                <div class="row">
                  <div class='col-12'>
                  {{form_comment  }}

                    <button type="submit" class="btn text-white" id="main-btn">نشر</button>
                  </div>
                </div>
              </form>
              <div class="col-md-12">
                    {% if  comments.count == 0 %}
                        <h3 class="text-center">لا توجد تعليقات </h3>
                    {% else %}
                        <h3 class="text-center">ألتعليقات ({{comments.count}})</h3>
                    {% endif %}
              </div>
              <div class="col-md-12">
                <!-- main comments  -->
                <ul class="list-group">
                  {% for comment in comments %}

                  <!-- Start comment -->
                  <li
                    class="list-group-item bg-white d-flex flex-wrap border rounded my-2 pt-3 position-relative"
                  >
                    <div class="row w-100">
                      <div class="col-12">
                        <div class="d-flex flex-wrap">
                          <div class="dropdown position-absolute">
                            <button
                              class=" "
                              type="button"
                              id="dropdownMenuButton1"
                              data-bs-toggle="dropdown"
                              aria-expanded="false"
                            >
                              <i class="fa-solid fa-ellipsis"></i>
                            </button>
                            <ul
                              class="dropdown-menu"
                              aria-labelledby="dropdownMenuButton1"
                            >
                              <li>
                                <a class="dropdown-item" href="#"
                                  >أخفاء التعليق</a
                                >
                              </li>
                              <li><a class="dropdown-item" href="#">حذف</a></li>
                              <li>
                                <a class="dropdown-item" href="#">ألابلاغ </a>
                              </li>
                            </ul>
                          </div>
                          <a
                            href="#"
                            class="user-name w-100 d-flex align-items-center text-decoration-none"
                          >
                            <img
                              src="{{user.profile.img.url}}"
                              class="img-fluid rounded-circle"
                              alt=""
                              style="width: 30px"
                            />
                            <small class="mx-2">{{comment.username}} </small>
                          </a>
                          <small
                            class="mx-2 position-absolute"
                            style="left: 10px; top: 22px"
                            >{{comment.date_comment}}</small
                          >
                          <p class="p-2 content-commemt lead fs-5">{{comment.content_comment}}</p>
                        </div>
                      </div>

                      <div class="col-12">
                        <div
                          class="like-reply d-flex w-100 flex-row justify-content-around mt-3"
                        >
                          <label class="active" id="like-comment">
                            <i class="fa-solid fa-thumbs-up"></i>
                            <span>أعجاب</span>
                          </label>
                          <label id="copy-comment">
                            <i class="fa-solid fa-share-from-square"></i>
                            <span> نسخ</span>
                          </label>
                        </div>
                      </div>
                    </div>
                  </li>
                  <!-- End comment -->
                  {% endfor %}
                </ul>
                <!-- End comments  -->
              </div>
            </div>
          </li>
          <!-- End post -->
        </ul>
      </div>
    </div>
  </div>
</main>
{% endblock content %}

my_website_dj/templates/blog/index.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

 
  <!-- Start main -->
  <main class="main overflow-hidden">
    <div class="container">
      <div class="row pt-3">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}">{{message}}</div>
            {% endfor %}
          {% endif %}
        </div>
        <div class="col-md-8 posts py-2">
          <ul class="list-group">
            {% for post in posts  %}



            <!-- Start post -->
            <li class="list-group-item post my-2">
              <div class="user-info d-flex position-relative justify-content-between align-items-center">
                <div class="d-flex justify-content-between align-items-center">
                  <a href="{{post.auth.profile.user.imgb}}" class="user text-decoration-none d-flex align-items-center">
                    <img src="{{post.auth.profile.img.url}}" class="img-fluid rounded-circle" alt="" />
                    <div class="mx-2">
                      <small>{{post.auth}}</small><br />
                    </div>
                  </a>
                  <small class="position-absolute data-time">
                    {{post.date_post}}
                  </small>
                </div>
                <div class="dropdown">
                  <i class="fa-solid fa-ellipsis fs-5" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    
                  </i>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    {% if post.auth == user  %}
                    <li><a class="dropdown-item" href="{% url 'delete_post' post.pk  %}">حذف</a></li>
                    <li><a class="dropdown-item" href="{% url 'update_post' post.id %}">تعديل المنشور</a></li>
                    {% endif %}
                    <li><a class="dropdown-item" href="#">حظر</a></li>
                    <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#share">مشاركة</a></li>
                    <li><a class="dropdown-item" href="#">أخفاء المنشور</a></li>
                    <li><a class="dropdown-item" href="#">ٌأبلاغ</a></li>
                  </ul>
                </div>
              </div>
              <div class="content-post my-2">
                <p class="my-3 lh-lg">
                  {{post}}

 
                </p>
              </div>
              <ul class="icons list-group flex-row justify-content-around position-relative">
                <li class="list-group-item like-post active">
                  <i class="fa-solid fa-thumbs-up"></i>
                  <small>أعجاب</small>
                </li>
                <li class="list-group-item comment-icon"  >
                  <a href="{% url 'detail' post.id %}" class="overflow-hidden">

                    <i class="fa-solid fa-comments"></i>
                    <small>ألتعليقات </small>
                  </a>
  
                </li>



                  <button class="btn-share" type="button" data-bs-toggle="modal" data-bs-target="#share">
                      <i class="fa-solid fa-share-from-square"></i>
                      <small>مشاركة</small>
                    
                  </button>



              </ul>




              
              <div class="box-comments  position-absolute w-100 overflow-hidden  z-index-100">
                <div class="container ">


                  <div class="modal fade" id="box-comments" tabindex="-1" aria-labelledby="scroll-title" style="display: none;" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable ">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          <a href="{% url 'detail' post.id %}" class="overflow-hidden"><h5 class="modal-title" id="scroll-title">ألتعليقات</h5></a>
                          
                        </div>
                        <div class="modal-body">
                          <!-- main comments  -->
                          <ul class="list-group">
                            <!-- Start comment -->
                            <li class="list-group-item bg-white d-flex flex-wrap border  rounded my-2 pt-3 position-relative ">
                              <div>
                                <div class="d-flex flex-wrap">
                                  <div class="dropdown position-absolute">
                                    <button class=" " type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
                                      aria-expanded="false">
                                      <i class="fa-solid fa-ellipsis"></i>
                                    </button>
                                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                      <li><a class="dropdown-item" href="#">أخفاء التعليق</a></li>
                                      <li><a class="dropdown-item" href="#">حذف</a></li>
                                      <li><a class="dropdown-item" href="#">ألابلاغ </a></li>
                                    </ul>
                                  </div>
                                  <a href="#" class="user-name fs-5 w-100 d-flex align-items-center text-decoration-none">
                                    <img src="{% static 'img/avatar-05.png' %}" class="img-fluid rounded-circle" alt="" style="width: 30px;"/>
                                    <small class="mx-2">miro </small>
                                    
                                  </a>
                                  <small class="mx-2 position-absolute" style='right: 80px;top: 22px;'>منذ 3 </small>
                                  <span class="p-2 content-commemt">هو شاعر من شعراء العصر المملوكي في مصر والذي كان من شعراء
                                    القرن الثامن الهجري والموافق الرابع عشر الميلادي</span>
                                </div>
                
                
                                <div class="like-reply d-flex w-100 justify-content-around mt-3">
                                  <label class="active">
                                    <i class="fa-solid fa-thumbs-up"></i>
                                    <span>أعجاب</span>
                                  </label>
                                  <label>
                                    <i class="fa-solid fa-copy" id="copy-comment"></i>
                                    <span> نسخ</span>
                                  </label>
                                </div>
                              </div>
                
                            </li>
                            <!-- End comment -->
                          </ul>
                          <!-- End comments  -->
                        </div>

                        
                        <div class="modal-footer">

                        </div>
                      </div>
                    </div>
                  </div>





                  <div class="modal fade w-100" id="share" tabindex="-1" aria-labelledby="share-title" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="share-title">مشاركة المنشور على ....</h5>
                          <button type="button" class="btn-close m-0" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                          <span class="rounded-circle  copy-link fs-2"><i class="fa-solid fa-copy"></i></span>
                        </div>
            
                      </div>
                    </div>
                  </div> 


                </div>
              </div>
            </li>
            <!-- End post -->
            {% endfor %}
          </ul>
        </div>
        <!-- Start popular-posts  -->
        <div class="col-md-4 popular-posts  py-2">
          <h5> المنشورات الرائجة</h5>
          <ul class="list-group">
            {% for post in posts %}
            <li class="list-group-item  d-flex overflow-hidden mt-2" >
              <span class="px-2" ><i class="fa-solid fa-share-from-square" data-bs-toggle="modal" data-bs-target="#share"></i></span>
              <a href="{% url 'detail' post.id %}" class="overflow-hidden"><small>{{post.content_post}}</small></a>
            </li>
            
            {% endfor %}


          </ul>
        </div>
        <!-- End popular-posts  -->
      </div>
    </div>
  </main>
  
  <!-- End main -->

{% endblock content %}

my_website_dj/templates/blog/new-post.html
{% extends 'base.html' %}
{% block content %}


    <!-- Start main -->
    <main class="main overflow-hidden">
        <div class="container">
            <div class="row pt-3">
                <div class="col-md-8 posts py-2">
                    <form>



                        <form class="row row-cols-lg-auto g-3 align-items-center">
                            <div class="col-12 form-floting">
                                <label class="my-2 " for="post-content">محتوى المنشور</label>
                                <div class="input-group">
                                    <textarea type="text" class="form-control" name="post-value" id="post-content"
                                        placeholder="محتوى المنشور"></textarea>
                                </div>
                            </div>

                            <div class=" col-2 px-2 my-3 form-check form-switch  d-flex justify-content-between ">
                                <input class="form-check-input" type="checkbox" id="post-active" checked>
                                <label class="form-check-label" for="post-active">نشط</label>
                            </div>
                            <div class="col-12 my-3">
                                <button type="submit" id="main-btn" class="btn btn-primary">نشر</button>
                            </div>
                        </form>
                    </form>
                </div>
            </div>
        </div>
    </main>
    <!-- End main -->


{% endblock content %}

my_website_dj/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

 
  <!-- Start main -->
  <main class="main overflow-hidden">
    <div class="container">
      <div class="row pt-3">

        <div class="col-md-8">
          <ul class="list-group posts">
            <!-- Start post -->
            <li class="list-group-item post my-2">
              <div class="user-info d-flex position-relative justify-content-between align-items-center">
                <div class="d-flex justify-content-between align-items-center">
                  <a href="#" class="user text-decoration-none d-flex align-items-center">
                    <img
                      src="{{object.auth.profile.img.url}}"
                      class="img-fluid rounded-circle"
                      alt=""
                    />
                    <div class="mx-2"><small>{{object.auth}}</small><br /></div>
                  </a>
                  <small class="position-absolute data-time">
                    {{object.date_post}}
                  </small>
                </div>

              </div>
              <div class="content-post my-2 ">
                <p class="my-3 lh-lg fs-4">{{object.content_post}}</p>
              </div>



            </li>
            <!-- End post -->
          </ul>
        </div>
        <div class="col-md-8">
          <form class=" g-3 justify-content-center" method='POST'>
            {% csrf_token %}

              <div class=" d-flex align-items-center ">
                <input type="submit" class="btn btn-primary" id='main-btn'  value='حذف'/>
                <a class="nav-link" href="{% url 'detail' object.pk  %}">الغاء</a>
              </div>
            </form>
        </div>
        <!-- Start popular-posts  -->
        <div class="col-md-4 popular-posts  py-2">
          <h5> المنشورات الرائجة</h5>
          <ul class="list-group">
            {% for post in posts %}
            <li class="list-group-item  d-flex overflow-hidden mt-2" >
              <span class="px-2" ><i class="fa-solid fa-share-from-square" data-bs-toggle="modal" data-bs-target="#share"></i></span>
              <a href="{% url 'detail' post.id %}" class="overflow-hidden"><small>{{post.content_post}}</small></a>
            </li>
            
            {% endfor %}


          </ul>
        </div>
        <!-- End popular-posts  -->
      </div>
    </div>
  </main>
  
  <!-- End main -->

{% endblock content %}

my_website_dj/templates/blog/update_post.html
{% extends 'base.html' %}
{% block content %}


    <!-- Start main -->
    <main class="main overflow-hidden">
        <div class="container">
            <div class="row pt-3">
                <div class="col-md-8 posts py-2">



                        <form class="row row-cols-lg-auto g-3 align-items-center" method="POST">
                            {% csrf_token %}
                            
                            {% comment %} {{form}} {% endcomment %}
                             <div class="col-12 form-floting">
                                <label class="my-2 " for="post-content">تعديل المنشور</label>
                                <div class="input-group">
                                    <textarea type="text" class="form-control" value name="content_post" id="id_content_post"
                                        placeholder="محتوى المنشور">{{object.content_post}}</textarea>
                                </div>
                            </div>

                            <div class="col-12 my-3">
                                <button type="submit" id="main-btn" class="btn btn-primary">حفظ</button>
                            </div>
                        </form>
                </div>
            </div>
        </div>
    </main>
    <!-- End main -->


{% endblock content %}